// <auto-generated />
using FinalProject_v1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FinalProject_v1.Migrations
{
    [DbContext(typeof(FinalProject_v1Context))]
    partial class FinalProject_v1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProjec_v1.Models.lead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("fName");

                    b.Property<string>("lName");

                    b.Property<string>("owner");

                    b.Property<int>("phone");

                    b.HasKey("ID");

                    b.ToTable("lead");
                });

            modelBuilder.Entity("FinalProject_v1.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fName");

                    b.Property<string>("lName");

                    b.Property<string>("password");

                    b.Property<string>("role");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("FinalProject_v1.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("administrator");

                    b.Property<bool>("user");

                    b.HasKey("ID");

                    b.ToTable("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
